### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by muhwagwa** [swsnu/swpp2021-team8#102]
- [x] Private 시 비밀번호 창
- [ ] Recommendation 변경
- [x] Bug fix- main page blackout, grouplist item.js 40째 줄
- [x] delete 실시간 타이머
- [x] member 차있는게 1/4이면 오른쪽 1/4이 빨간색으로 칠해지는 것 같은데 유저 입장에서 좌측 1/4이 칠해지는 게 더 좋아보입니다!
- [x] /group/create에서 OTT에 대한 가격, 인원 정보에 커서를 올리면 input 처럼 커서가 변해서 혼란을 줄 수 있을 것 같습니다!
- [x] My group에 다음과 같이 표시되는데 이건 그룹 하나를 들어갔다는 의미인가요? (단순 질문, answered)
- [x] My group 부분은 위와 같이 아직 빈 칸으로 보이는데 아직 구현이 되지 않은 것인지 궁금합니다!
- [x] 추가로 "My Groups"라고 적힌 부분 자체를 눌러도 마이페이지로 연결되면 좋을 것 같습니다!
- [x] 그룹에서 나갈 수 있는 방법이 있나요? (단순 질문, answered)
- [ ] 디즈니 플러스 그룹을 생성하려고 했는데 생성이 안 됩니다
- [x] 마이페이지에 가입한 그룹이 뜨지 않습니다ㅠ
- [x] 마이페이지에 캘린더는 무슨 용도인가요? (단순 질문, answered)
- [x] Content에서 오른쪽 화살표로 넘기다가 왼쪽으로 다시 넘기면 영화가 복사되는 버그가 있는 것 같습니다!
- [x] 유저 이름이 길어질 경우 이름이 겹쳐보입니다
- [x] mygroups 아래 초록색 동그라미 눌러도 그룹 확인가능하면 더 좋을 것 같습니다 :)
- [x] 가입한 그룹이 있으면 Payment day에 마킹이 되는데 현재 MyPage에서 가입한 그룹이 보이지 않는 이슈가 있네요
- [x] recommendation contents, trending contents 화살표 클릭 시 영화 이미지를 담고 있는 부분이 중앙으로 올라왔다가 내려가는 것처럼 보입니다
- [x] 마이페이지 마이그룹이 로딩시 반짝하고 떴다가 바로 사라지네요
- [x] 서비스 관련 질문인데 계좌번호를 저렇게 공개적으로 보여주는건 전혀 문제가 없는지 궁금합니다
- [x] mygroup 생성할 때 정보들을 입력하지 않으면 생성이 안되는데 어떤 정보가 missing 됐는지 알려주면 좋을 것 같습니다
- [x] payday라는 용어에 대한 설명이 있으면 좋을 것 같습니다!
- [x] 참여 그룹 관련 버그 같은데, 저 같은 경우엔 my groups 리스트에는 그룹이 보이는데, 들어가면 quit 버튼이 보이지 않습니다!

**Comment by cw10108** [comment]
### Assign - Chiwon
 1 password prompt when private
 6 create cursor
 15 detail name overriding
 20 blur account number when not joined
 21 groupcreate missing info
 22 payday description
 23 quit button not seen

**Comment by arclic** [comment]
## Assign - Jooyoung
Bug fix- main page blackout, grouplist item.js 40째 줄
delete 실시간 타이머
member 차있는게 1/4이면 오른쪽 1/4이 빨간색으로 칠해지는 것 같은데 유저 입장에서 좌측 1/4이 칠해지는 게 더 좋아보입니다!
My group 부분은 위와 같이 아직 빈 칸으로 보이는데 아직 구현이 되지 않은 것인지 궁금합니다!
 추가로 "My Groups"라고 적힌 부분 자체를 눌러도 마이페이지로 연결되면 좋을 것 같습니다!
Content에서 오른쪽 화살표로 넘기다가 왼쪽으로 다시 넘기면 영화가 복사되는 버그가 있는 것 같습니다!
유저 이름이 길어질 경우 이름이 겹쳐보입니다
 mygroups 아래 초록색 동그라미 눌러도 그룹 확인가능하면 더 좋을 것 같습니다 :)
가입한 그룹이 있으면 Payment day에 마킹이 되는데 현재 MyPage에서 가입한 그룹이 보이지 않는 이슈가 있네요
recommendation contents, trending contents 화살표 클릭 시 영화 이미지를 담고 있는 부분이 중앙으로 올라왔다가 내려가는 것처럼 보입니다
