### ISSUE TITLE
[Bug/Enhancement] Bug Fix after Alpha test

### ISSUE THREAD

**Issue by arclic** [swsnu/swpp2021-team8#110]
## Todos
- [ ] Bug fix- main page blackout, grouplist item.js 40째 줄
- [x] delete 실시간 타이머
- [x] member 차있는게 1/4이면 오른쪽 1/4이 빨간색으로 칠해지는 것 같은데 유저 입장에서 좌측 1/4이 칠해지는 게 더 좋아보입니다!
- [x] My group 부분은 위와 같이 아직 빈 칸으로 보이는데 아직 구현이 되지 않은 것인지 궁금합니다!
- [x] 추가로 "My Groups"라고 적힌 부분 자체를 눌러도 마이페이지로 연결되면 좋을 것 같습니다!
- [x] Content에서 오른쪽 화살표로 넘기다가 왼쪽으로 다시 넘기면 영화가 복사되는 버그가 있는 것 같습니다!
- [x] mygroups 아래 초록색 동그라미 눌러도 그룹 확인가능하면 더 좋을 것 같습니다 :)
- [x] 가입한 그룹이 있으면 Payment day에 마킹이 되는데 현재 MyPage에서 가입한 그룹이 보이지 않는 이슈가 있네요
- [x] recommendation contents, trending contents 화살표 클릭 시 영화 이미지를 담고 있는 부분이 중앙으로 올라왔다가 내려가는 것처럼 보입니다

**Comment by cw10108** [comment]
Bug fix- grouplist item.js 40째 줄
I'll handle this
