### ISSUE TITLE
[Feature] Add push notification

### ISSUE THREAD

**Issue by arclic** [swsnu/swpp2021-team8#112]
## Todos
- [ ] Group creation notification
- [ ] Group payday notification
- [ ] Group deletion notification

**Comment by arclic** [comment]
https://pypi.org/project/django-notifications-hq/
https://medium.com/star-gazers/how-to-add-notifications-to-django-app-74df1dac984e
