### ISSUE TITLE
[Feature] Implement MainPage Container

### ISSUE THREAD

**Issue by arclic** [swsnu/swpp2021-team8#17]
## Todos
- [x]  Implement MainPage Group/Content Tab
- [x]  Design Group/Content Search
- [x] Create New Group Button
- [x] Implement Group List
- [x] Implement Group Search
- [x] Implement Recommendation Contents
- [x] Implement Trending Contents
- [x] Implement Content Search
