### ISSUE TITLE
[Feature] Implement content detail page

### ISSUE THREAD

**Issue by arclic** [swsnu/swpp2021-team8#37]
## Todos
 - [x] Request Movie detail data from TheMovieDBAPI
 - [x] Request available OTT platform for content
 - [x] Render it in Content detail page
 - [ ] Test
