### ISSUE TITLE
[Enhancement] Enhancement ContentListItem

### ISSUE THREAD

**Issue by arclic** [swsnu/swpp2021-team8#48]
## Todos
 - [ ] Prevent user from clicking image when image is placeholder image
 - [ ] Set fixed image size, but responsive
 - [ ] Add a loading effect when image is loading
