### ISSUE TITLE
[Feature] Show current group status on Header

### ISSUE THREAD

**Issue by arclic** [swsnu/swpp2021-team8#50]
## Todos
- [ ] Design group status bar
- [ ] Get current group status from backend
- [ ] Show group status on Header
