### ISSUE TITLE
[Bug] Fix Travis CI errors

### ISSUE THREAD

**Issue by arclic** [swsnu/swpp2021-team8#51]
## Todos
- [x] Fix eslint error
- [x] Fix frontend test error
- [x] Fix pylint error
- [x] Fix python test error
