### ISSUE TITLE
[Enhancement] Enhancement MainPage

### ISSUE THREAD

**Issue by arclic** [swsnu/swpp2021-team8#83]
## Todos
- [x] Fix Group search filters
- [x] Fix Group List headers
- [x] Remove unnecessary border line
