### ISSUE TITLE
[Feature] Update MyPage Section

### ISSUE THREAD

**Issue by arclic** [swsnu/swpp2021-team8#84]
## Todos
- [ ] Display User info
- [ ] Display User's group info
- [ ] Display next payment date
