### ISSUE TITLE
[Feature] Deployment via AWS 

### ISSUE THREAD

**Issue by arclic** [swsnu/swpp2021-team8#88]
## Todos
- [ ] Deploy via AWS
- [ ] Set up HTTPS
- [ ] Get public domain
